create table if not exists public.stock_rating_history (
  id bigint generated by default as identity primary key,
  rating_date date not null,
  ticker text not null check (ticker ~ '^[A-Z][A-Z.-]{0,5}$'),
  algorithm_version text not null,
  rating text not null check (rating in ('BUY_SETUP','HOLD_WAIT','AVOID','NOT_RATED')),
  technical_state text not null,
  fundamental_state text not null,
  setup text,
  market_regime text,
  entry_price numeric not null check (entry_price > 0),
  benchmark_price numeric check (benchmark_price > 0),
  edge_score smallint check (edge_score between 0 and 100),
  technical_score smallint check (technical_score between 0 and 100),
  fundamental_score smallint check (fundamental_score between 0 and 100),
  entry_low numeric,
  entry_high numeric,
  stop_price numeric,
  target_price numeric,
  inputs jsonb not null default '{}'::jsonb,
  sessions_observed smallint not null default 0 check (sessions_observed between 0 and 60),
  last_observed_date date,
  latest_price numeric,
  latest_benchmark_price numeric,
  return_5d numeric,
  return_10d numeric,
  return_20d numeric,
  return_60d numeric,
  spy_return_5d numeric,
  spy_return_10d numeric,
  spy_return_20d numeric,
  spy_return_60d numeric,
  max_return numeric,
  max_drawdown numeric,
  close_outcome text check (close_outcome in ('TARGET','STOP') or close_outcome is null),
  close_outcome_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (rating_date, ticker, algorithm_version)
);

alter table public.stock_rating_history enable row level security;
revoke all on table public.stock_rating_history from anon, authenticated;
revoke all on sequence public.stock_rating_history_id_seq from anon, authenticated;

create index if not exists idx_stock_rating_history_unresolved
  on public.stock_rating_history (sessions_observed, rating_date, ticker)
  where sessions_observed < 60;

create index if not exists idx_stock_rating_history_reporting
  on public.stock_rating_history (rating, rating_date desc);

comment on table public.stock_rating_history is
  'Forward-only, point-in-time stock ratings. Written and read through authenticated server endpoints using the service role; no direct client access.';
